resource "aws_kms_key" "tfer--b5361b7b-ea33-4269-aac9-ebe882ac7fb7" {
  customer_master_key_spec = "SYMMETRIC_DEFAULT"
  description              = "Used for access to S3 bucket where Geisinger Kit data is extracted to."
  enable_key_rotation      = "false"
  is_enabled               = "true"
  key_usage                = "ENCRYPT_DECRYPT"
  multi_region             = "false"
  policy                   = "{\"Id\":\"key-consolepolicy-3\",\"Statement\":[{\"Action\":\"kms:*\",\"Effect\":\"Allow\",\"Principal\":{\"AWS\":\"arn:aws:iam::650251715284:root\"},\"Resource\":\"*\",\"Sid\":\"Enable IAM User Permissions\"},{\"Action\":[\"kms:Create*\",\"kms:Describe*\",\"kms:Enable*\",\"kms:List*\",\"kms:Put*\",\"kms:Update*\",\"kms:Revoke*\",\"kms:Disable*\",\"kms:Get*\",\"kms:Delete*\",\"kms:TagResource\",\"kms:UntagResource\",\"kms:ScheduleKeyDeletion\",\"kms:CancelKeyDeletion\",\"kms:RotateKeyOnDemand\"],\"Effect\":\"Allow\",\"Principal\":{\"AWS\":[\"arn:aws:iam::650251715284:user/avi@opmed.ai\",\"arn:aws:iam::650251715284:user/andrew@opmed.ai\",\"arn:aws:iam::650251715284:user/moshe@opmed.ai\"]},\"Resource\":\"*\",\"Sid\":\"Allow access for Key Administrators\"},{\"Action\":[\"kms:Encrypt\",\"kms:Decrypt\",\"kms:ReEncrypt*\",\"kms:GenerateDataKey*\",\"kms:DescribeKey\"],\"Effect\":\"Allow\",\"Principal\":{\"AWS\":[\"arn:aws:iam::650251715284:user/avi@opmed.ai\",\"arn:aws:iam::650251715284:user/andrew@opmed.ai\",\"arn:aws:iam::650251715284:user/moshe@opmed.ai\"]},\"Resource\":\"*\",\"Sid\":\"Allow use of the key\"},{\"Action\":[\"kms:CreateGrant\",\"kms:ListGrants\",\"kms:RevokeGrant\"],\"Condition\":{\"Bool\":{\"kms:GrantIsForAWSResource\":\"true\"}},\"Effect\":\"Allow\",\"Principal\":{\"AWS\":[\"arn:aws:iam::650251715284:user/avi@opmed.ai\",\"arn:aws:iam::650251715284:user/andrew@opmed.ai\",\"arn:aws:iam::650251715284:user/moshe@opmed.ai\"]},\"Resource\":\"*\",\"Sid\":\"Allow attachment of persistent resources\"},{\"Action\":[\"kms:GenerateDataKey\",\"kms:Decrypt\"],\"Effect\":\"Allow\",\"Principal\":{\"AWS\":\"arn:aws:iam::650251715284:role/service-role/geisinger_kit_extraction-role-af22biti\"},\"Resource\":\"*\",\"Sid\":\"AllowLambdaToUseKMSKey\"},{\"Action\":[\"kms:Encrypt\",\"kms:Decrypt\",\"kms:ReEncrypt*\",\"kms:GenerateDataKey*\",\"kms:DescribeKey\"],\"Effect\":\"Allow\",\"Principal\":{\"AWS\":\"arn:aws:iam::650251715284:role/service-role/s3crr_role_for_geisinger-data-bucket\"},\"Resource\":\"*\",\"Sid\":\"Allow use of the key for replication\"},{\"Action\":\"kms:Decrypt\",\"Effect\":\"Allow\",\"Principal\":{\"AWS\":\"arn:aws:iam::851725650090:role/iam_fetch-data__role\"},\"Resource\":\"*\"}],\"Version\":\"2012-10-17\"}"
}
